security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: false
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator

        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_front_login
                check_path: app_front_login_check
                default_target_path: app_front_passport

            logout:
                path: app_front_logout
                target: app_front_login

    access_control:
        - { path: ^/api/login$, roles: PUBLIC_ACCESS }
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/app, roles: ROLE_USER }