# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    spotify.client_id: '%env(string:SPOTIFY_CLIENT_ID)%'
    spotify.client_secret: '%env(string:SPOTIFY_CLIENT_SECRET)%'
    spotify.redirect_uri: '%env(string:SPOTIFY_REDIRECT_URI)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    App\Service\SpotifyOAuthService:
        arguments:
            $spotifyClientId: '%spotify.client_id%'
            $spotifyClientSecret: '%spotify.client_secret%'
            $spotifyRedirectUri: '%spotify.redirect_uri%'